// This file was auto-generated by ML.NET Model Builder. 

using System;
using ModelTrainer_v2ML.Model;

namespace ModelTrainer_v2ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                SepalLength = 5.1F,
                SepalWidth = 3.5F,
                PetalLength = 1.4F,
                PetalLWidth = 0.2F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Type with predicted Type from sample data...\n\n");
            Console.WriteLine($"SepalLength: {sampleData.SepalLength}");
            Console.WriteLine($"SepalWidth: {sampleData.SepalWidth}");
            Console.WriteLine($"PetalLength: {sampleData.PetalLength}");
            Console.WriteLine($"PetalLWidth: {sampleData.PetalLWidth}");
            Console.WriteLine($"\n\nPredicted Type value {predictionResult.Prediction} \nPredicted Type scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
