// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ModelTrainer_v2ML.Model
{
    public class ModelInput
    {
        [ColumnName("SepalLength"), LoadColumn(0)]
        public float SepalLength { get; set; }


        [ColumnName("SepalWidth"), LoadColumn(1)]
        public float SepalWidth { get; set; }


        [ColumnName("PetalLength"), LoadColumn(2)]
        public float PetalLength { get; set; }


        [ColumnName("PetalLWidth"), LoadColumn(3)]
        public float PetalLWidth { get; set; }


        [ColumnName("Type"), LoadColumn(4)]
        public string Type { get; set; }


    }
}
